export const constants = {
  ERROR_1: "Invalid email address",
  ERROR_2: "Password must be at least 8 characters in length",
  ERROR_3: "User does not belong to any account",
  ERROR_4: "Invalid email or password",
  ERROR_5: "This email is already registered",
  EMAIL_REQ: "Please enter email address",
  PASS_REQ: "Please enter password",
  EMAIL: "Enter valid e-mail address",
  SOMETHING_WRONG: "Something went wrong!",
  ERROR_6: "Please enter section type",
  ERROR_7: "Section type already exists",
  SUCC_1: "Section created successfully",
  SUCC_4: "Section data deleted successfully",
  ERROR_8: "Please enter section id",
  ERROR_9: "Section data not found",
  SUCC_3: "Section data updated successfully",
  ERROR_TITLE: "Please enter title",
  ERROR_TITLE_1: "Please enter title 1",
  ERROR_CARD_1_TITLE: "Please enter card 1 title",
  ERROR_CARD_2_TITLE: "Please enter card 2 title",
  ERROR_Q1_TITLE: "Please enter q1 title",
  ERROR_Q2_TITLE: "Please enter q2 title",
  ERROR_Q3_TITLE: "Please enter q3 title",
  ERROR_Q4_TITLE: "Please enter q4 title",
  MIN_MAX_TITLE: "Please enter title between 5 to 60 characters",
  MIN_MAX_TITLE_1: "Please enter title 1 between 5 to 60 characters",
  MIN_MAX_CARD_TITLE_1: "Please enter card 1 title between 5 to 60 characters",
  MIN_MAX_CARD_TITLE_2: "Please enter card 2 title between 5 to 60 characters",
  MIN_MAX_Q1_TITLE: "Please enter q1 title between 5 to 60 characters",
  MIN_MAX_Q2_TITLE: "Please enter q2 title between 5 to 60 characters",
  MIN_MAX_Q3_TITLE: "Please enter q3 title between 5 to 60 characters",
  MIN_MAX_Q4_ITLE: "Please enter q4 title between 5 to 60 characters",
  ERROR_DESCRIPTION: "Please enter description",
  ERROR_DESCRIPTION_1: "Please enter description 1",
  ERROR_DESCRIPTION_2: "Please enter description 2",
  ERROR_DESCRIPTION_3: "Please enter description 3",
  ERROR_DESCRIPTION_4: "Please enter description 4",
  MIN_MAX_DESCRIPTION: "Please enter description between 5 to 200 characters",
};
